# ./docker-compose.yml

version: "3"

services:
  mysql-server:
    image: mysql:5.7
    container_name: mysql57server
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: forumdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  web-server:
    build:
      context: ./
    container_name: php7apache2
    depends_on:
      - mysql-server
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
